### ISSUE TITLE
艦娘を編成から外した時にエラーが出る

### ISSUE THREAD

**Issue by Nishisonic** [ponkotuy/MyFleetGirls#357]
旗艦以外を編成から外そうとすると、IndexOutOfBoundsExceptionが発生します
一応ご報告

**Comment by ponkotuy** [comment]
単純には再現しないですね。何か条件がありそうです

**Comment by Nishisonic** [comment]
なぜか発生しなくなりました…
ちょっと条件が掴めませんので、何か分かりましたらまたご報告させて頂きます

**Comment by ponkotuy** [comment]
よくわからんけど出ちゃった、という人はMyFleetGirlsを再起動すればなおります

**Comment by ponkotuy** [comment]
多分最近追加された艦隊編成登録まわりの機能を使うと起こりそう

**Comment by Nishisonic** [comment]
その通りです

艦隊編成記録起動後、艦娘を第一艦隊から外した際に発生しました
エラーログちゃんと見ておけば良かったです、すいません

**Comment by harry0000** [comment]
昔発生してて最近は全く起きてなかったのですが、今再現方法わかりました(思い出しました？)

1. 1隻だけ配置した状態で艦これ起動
2. 編成展開で6隻編成の第一艦隊を展開
3. 第一艦隊の2番目の艦をドラッグ&ドロップで艦隊から外す
4. java.lang.IndexOutOfBoundsException

以降2番目の艦をドラッグ&ドロップで外すたびにjava.lang.IndexOutOfBoundsExceptionが発生します

```
myfleetgirls.keystoreに変更はありません
LICENSEに変更はありません
application.conf.sampleに変更はありません
MyFleetGirls.jarに変更はありません

---------------------------------------------
  Welcome to MyFleetGirls Client Ver 1.5.2
---------------------------------------------

Ver1.5.2 バグ修正(JSONParseErrorなど)

18:43:00.317 [main] INFO  o.l.p.i.DefaultHttpProxyServer - Starting proxy at address: localhost/127.0.0.1:8080
18:43:00.348 [main] INFO  o.l.p.i.DefaultHttpProxyServer - Proxy listening with TCP transport
18:43:00.457 [main] INFO  o.l.p.i.DefaultHttpProxyServer - Proxy started at address: /127.0.0.1:8080
/kcs/mainD2.swf
/kcsapi/api_start2
/kcsapi/api_req_member/get_incentive
/kcsapi/api_get_member/require_info
/kcsapi/api_port/port
所属： 単冠湾泊地

============================================
パスワード認証無し
MyFleetGirlsサーバへの接続に成功しました
URL: https://myfleet.moe/user/14082837
============================================

所持装備数 -> 1048
所持艦娘数 -> 239
燃料 -> 210651, 弾薬 -> 209687, 鉄鋼 -> 251265, ボーキサイト -> 167476, 高速建造材 -> 3000,  高速修復材 -> 2172, 開発資材 -> 2448, 改修資材 -> 15
ID -> 1, ShipID -> 5635, 入渠完了時間 -> 2016/06/23 21:25
ID -> 2, ShipID -> 44, 入渠完了時間 -> 2016/06/23 19:49
ID -> 1, 名前 -> 第1艦隊, 艦娘 -> (3173), 遠征 ->
ID -> 2, 名前 -> 第2艦隊, 艦娘 -> (16, 64, 10, 1), 遠征 -> (ID -> 1-2, 遠征完了時間 -> 2016/06/23 18:47)
ID -> 3, 名前 -> 第3艦隊, 艦娘 -> (3627, 2954, 28347, 75, 27414, 27941), 遠征 -> (ID -> 1-38, 遠征完了時間 -> 2016/06/23 21:12)
ID -> 4, 名前 -> 第4艦隊, 艦娘 -> (59, 7, 116, 149, 5), 遠征 -> (ID -> 1-21, 遠征完了時間 -> 2016/06/23 20:07)
Lv -> 112, 経験値 -> 7621468
/kcsapi/api_get_member/preset_deck
/kcsapi/api_req_hensei/preset_select
/kcsapi/api_req_hensei/change
java.lang.IndexOutOfBoundsException: 1
        at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:65)
        at scala.collection.immutable.List.apply(List.scala:84)
        at com.ponkotuy.restype.HenseiChange$$anonfun$postables$1.apply$mcZI$sp(HenseiChange.scala:24)
        at com.ponkotuy.restype.HenseiChange$$anonfun$postables$1.apply(HenseiChange.scala:24)
        at com.ponkotuy.restype.HenseiChange$$anonfun$postables$1.apply(HenseiChange.scala:24)
        at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
        at scala.collection.TraversableLike$class.filterNot(TraversableLike.scala:267)
        at scala.collection.AbstractTraversable.filterNot(Traversable.scala:104)
        at com.ponkotuy.restype.HenseiChange$.postables(HenseiChange.scala:24)
        at com.ponkotuy.http.ControllerActor$$anonfun$receive$2.applyOrElse(PostActor.scala:61)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
        at com.ponkotuy.http.ControllerActor.aroundReceive(PostActor.scala:54)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ponkotuy** [comment]
艦の数を編成展開で増やすとエラーって感じする

**Comment by ponkotuy** [comment]
まぁ編成展開に対応してないのがわるい。はー対応するかー…
