### ISSUE TITLE
編成展開を行うとjava.lang.NumberFormatExceptionが発生する

### ISSUE THREAD

**Issue by harry0000** [ponkotuy/MyFleetGirls#358]
今のところ常に発生します。

* MyFleetGirls Ver 1.5.3
* Windows 10 (64bit)
* IE 11? (KanColleViewer Version 4.2.4)
* 編成記録枠3つの状態で、どれを選択しても発生

発生時のログを見ると、[/library/src/main/scala/com/ponkotuy/data/PresetSelect.scala#L27](https://github.com/ponkotuy/MyFleetGirls/blob/ebeca5a5d841e4ce03836380f07161111985aeb6/library/src/main/scala/com/ponkotuy/data/PresetSelect.scala#L27)の`api_name_id.toLong`で`"".toLong`が実行されているようです(?)。

```
ID -> 1, 名前 -> 第1艦隊, 艦娘 -> (28108, 13907, 14342, 5828, 323, 1771), 遠征 ->
ID -> 2, 名前 -> 第2艦隊, 艦娘 -> (16, 64, 10, 1), 遠征 -> (ID -> 1-2, 遠征完了時間 -> 2016/06/24 22:10)
ID -> 3, 名前 -> 第3艦隊, 艦娘 -> (2954, 3627, 28347, 75, 27414, 27941), 遠征 -> (ID -> 1-38, 遠征完了時間 -> 2016/06/24 23:03)
ID -> 4, 名前 -> 第4艦隊, 艦娘 -> (59, 7, 116, 149, 5), 遠征 -> (ID -> 1-21, 遠征完了時間 -> 2016/06/24 23:31)
Lv -> 112, 経験値 -> 7629249
/kcsapi/api_get_member/preset_deck
/kcsapi/api_req_hensei/preset_select
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:601)
        at java.lang.Long.parseLong(Long.java:631)
        at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:276)
        at scala.collection.immutable.StringOps.toLong(StringOps.scala:29)
        at com.ponkotuy.data.PresetSelect$RawPresetSelect.build(PresetSelect.scala:27)
        at com.ponkotuy.data.PresetSelect$$anonfun$fromJson$1.apply(PresetSelect.scala:16)
        at com.ponkotuy.data.PresetSelect$$anonfun$fromJson$1.apply(PresetSelect.scala:16)
        at scala.Option.map(Option.scala:146)
        at com.ponkotuy.data.PresetSelect$.fromJson(PresetSelect.scala:16)
        at com.ponkotuy.restype.PresetSelect$.postables(PresetSelect.scala:14)
        at com.ponkotuy.http.ControllerActor$$anonfun$receive$2.applyOrElse(PostActor.scala:61)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
        at com.ponkotuy.http.ControllerActor.aroundReceive(PostActor.scala:54)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ponkotuy** [comment]
あそこに空文字列入る可能性あるの…マジ艦これのエンジニアクソだろ…許し難い…

**Comment by ponkotuy** [comment]
とりま原因は分かったのではやいとこなおします
